### ISSUE TITLE
springboot使用application.properties 出现 java.lang.String cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by yuanxiang250** [louislivi/fastdep#10]
![图片](https://user-images.githubusercontent.com/11846695/93894056-e6babd00-fd20-11ea-985f-8c0696b0fb3c.png)

**Comment by yuanxiang250** [comment]
configuration.setPort(Integer.valueOf(map.get("port") + ""));
  configuration.setDatabase(Integer.valueOf(map.get("database") + ""));

**Comment by yuanxiang250** [comment]
configuration.setPort(Integer.valueOf(map.get("port") + ""));
            configuration.setDatabase(Integer.valueOf(map.get("database") + ""));

**Comment by louislivi** [comment]
这个问题在master分支中已经修复
