### ISSUE TITLE
配置文件的database是什么意思

### ISSUE THREAD

**Issue by trxrjgc** [louislivi/fastdep#11]
配置文件设置了不同的database
fastdep:
  redis:
    redis6379: #连接名称
      database: 0
      host: 127.0.0.1
      port: 6379
      lettuce: #下面为连接池的补充设置
        shutdown-timeout: 100 # 关闭超时时间
        pool:
          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
    redis6380: #连接名称
      database: 1
      host: 127.0.0.1
      port: 6380
      lettuce: #下面为连接池的补充设置
        shutdown-timeout: 100 # 关闭超时时间
        pool:
          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
    redis6381: #连接名称
      database: 2
      host: 127.0.0.1
      port: 6381
      lettuce: #下面为连接池的补充设置
        shutdown-timeout: 100 # 关闭超时时间
        pool:
          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
存入redis，三个redis还是存在0号库

**Comment by louislivi** [comment]
贴出业务代码看看呢

**Comment by tanrenxuan9751** [comment]
@SpringBootTest(classes = RedisClusterApplication.class)
@RunWith(SpringRunner.class)
public class RedisClusterTest {

    @Autowired
    private RedisTemplate<String, String> redis6379StringRedisTemplate;

    @Autowired
    private RedisTemplate<String, String> redis6380StringRedisTemplate;

    @Autowired
    private RedisTemplate<String, String> redis6381StringRedisTemplate;
    @Test
    public void test1(){
        redis6379StringRedisTemplate.boundValueOps("StringKey").set("StringValue");
        redis6379StringRedisTemplate.boundZSetOps("zSetKey").add("zSetVaule", 100D);
    }
}

**Comment by trxrjgc** [comment]
> 贴出业务代码看看呢

public class RedisClusterTest {

    @Autowired
    private RedisTemplate<String, String> redis6379StringRedisTemplate;

    @Autowired
    private RedisTemplate<String, String> redis6380StringRedisTemplate;

    @Autowired
    private RedisTemplate<String, String> redis6381StringRedisTemplate;
    @Test
    public void test1(){
        redis6379StringRedisTemplate.boundValueOps("StringKey").set("StringValue");
        redis6379StringRedisTemplate.boundZSetOps("zSetKey").add("zSetVaule", 100D);
    }
}
