### ISSUE TITLE
只能配置两个redis数据源，我配置了五个，启动报错

### ISSUE THREAD

**Issue by Junya520** [louislivi/fastdep#15]
报错信息：

APPLICATION FAILED TO START
***************************

Description:

Field stringRedisTemplate in com.liuqi.utils.MethodLimit required a single bean, but 5 were found:
	- redis0StringRedisTemplate: defined in null
	- redis1StringRedisTemplate: defined in null
	- redis2StringRedisTemplate: defined in null
	- redis3StringRedisTemplate: defined in null
	- redis4StringRedisTemplate: defined in null

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

Process finished with exit code 1

感觉应该是在源码的文件里修改配置，具体的不太会，请问应该怎么配置呢？

**Comment by Junya520** [comment]
redis配置：
fastdep:
  redis:
    redis0: #连接名称
      database: 0
      host: 127.0.0.1
      port: 6379
      lettuce: #下面为连接池的补充设置
        shutdown-timeout: 100 # 关闭超时时间
        pool:
          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
    redis1: #连接名称
      database: 4
      host: 127.0.0.1
      port: 6379
      lettuce: #下面为连接池的补充设置
        shutdown-timeout: 100 # 关闭超时时间
        pool:
          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
    redis2: #连接名称
      database: 25
      host: 127.0.0.1
      port: 6379
      lettuce: #下面为连接池的补充设置
        shutdown-timeout: 100 # 关闭超时时间
        pool:
          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
    redis3: #连接名称
      database: 26
      host: 127.0.0.1
      port: 6379
      lettuce: #下面为连接池的补充设置
        shutdown-timeout: 100 # 关闭超时时间
        pool:
          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接


    redis4: #连接名称
      database: 27
      host: 127.0.0.1
      port: 6379
      lettuce: #下面为连接池的补充设置
        shutdown-timeout: 100 # 关闭超时时间
        pool:
          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接

**Comment by Junya520** [comment]
完整的报错信息：

2020-11-21 08:57:49.169  INFO 14328 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed
2020-11-21 08:57:49.169  INFO 14328 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-2} closed
2020-11-21 08:57:49.390  INFO 14328 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-11-21 08:57:49.419  INFO 14328 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-11-21 08:57:49.423 ERROR 14328 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field stringRedisTemplate in com.liuqi.utils.MethodLimit required a single bean, but 5 were found:
	- redis0StringRedisTemplate: defined in null
	- redis1StringRedisTemplate: defined in null
	- redis2StringRedisTemplate: defined in null
	- redis3StringRedisTemplate: defined in null
	- redis4StringRedisTemplate: defined in null


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed


Process finished with exit code 1

**Comment by louislivi** [comment]
com.liuqi.utils.MethodLimit  中的 stringRedisTemplate **不要直接写stringRedisTemplate** 理应使用哪个源，就将变量名改为redis0StringRedisTemplate - redis4StringRedisTemplate的其中一个，会根据变量名自动检索到对应的数据源 ，也可以使用`@Qualifier("redis0StringRedisTemplate")`指定数据源。
详情见[文档地址](https://fastdep.louislivi.com/#/module/fastdep-redis?id=%e8%bf%90%e7%94%a8)

**Comment by Junya520** [comment]
@Component
public class RedisStringManyRepository {
    @Autowired
    @Qualifier("redis0StringRedisTemplate")
    private StringRedisTemplate redis0StringRedisTemplate;
    @Autowired
    @Qualifier("redis1StringRedisTemplate")
    private StringRedisTemplate redis1StringRedisTemplate;
    @Autowired
    @Qualifier("redis2StringRedisTemplate")
    private StringRedisTemplate redis2StringRedisTemplate;
    @Autowired
    @Qualifier("redis3StringRedisTemplate")
    private StringRedisTemplate redis3StringRedisTemplate;
    @Autowired
    @Qualifier("redis4StringRedisTemplate")
    private StringRedisTemplate redis4StringRedisTemplate;


    public StringRedisTemplate stringRedisTemplate(String name) {

        StringRedisTemplate stringRedisTemplate;
        switch (name) {
            case "4":
                stringRedisTemplate = redis1StringRedisTemplate;
                break;
            case "25":
                stringRedisTemplate = redis2StringRedisTemplate;
                break;
            case "26":
                stringRedisTemplate = redis3StringRedisTemplate;
                break;
            case "27":
                stringRedisTemplate = redis4StringRedisTemplate;
                break;
            default:
                stringRedisTemplate = redis0StringRedisTemplate;
                break;
        }

--------------------------------------------------------------------------------------------------------------------------

@Component
public class RedisStringManyRepository {
    @Autowired
    private StringRedisTemplate redis0StringRedisTemplate;
    @Autowired
    private StringRedisTemplate redis1StringRedisTemplate;
    @Autowired
    private StringRedisTemplate redis2StringRedisTemplate;
    @Autowired
    private StringRedisTemplate redis3StringRedisTemplate;
    @Autowired
    private StringRedisTemplate redis4StringRedisTemplate;


    public StringRedisTemplate stringRedisTemplate(String name) {

        StringRedisTemplate stringRedisTemplate;
        switch (name) {
            case "4":
                stringRedisTemplate = redis1StringRedisTemplate;
                break;
            case "25":
                stringRedisTemplate = redis2StringRedisTemplate;
                break;
            case "26":
                stringRedisTemplate = redis3StringRedisTemplate;
                break;
            case "27":
                stringRedisTemplate = redis4StringRedisTemplate;
                break;
            default:
                stringRedisTemplate = redis0StringRedisTemplate;
                break;
        }



我试了 这两种办法都不行  注入不到
报错信息：

APPLICATION FAILED TO START
***************************

Description:

Field stringRedisTemplate in com.liuqi.utils.MethodLimit required a single bean, but 5 were found:
	- redis0StringRedisTemplate: defined in null
	- redis1StringRedisTemplate: defined in null
	- redis2StringRedisTemplate: defined in null
	- redis3StringRedisTemplate: defined in null
	- redis4StringRedisTemplate: defined in null


Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed


Process finished with exit code 1



请问应该怎么解决呢 谢谢大佬

**Comment by louislivi** [comment]
`com.liuqi.utils.MethodLimit`里面也需要改变这里面有一个注入

**Comment by Junya520** [comment]
@component
public class MethodLimit {
@Autowired
private StringRedisTemplate redis0StringRedisTemplate;
@Autowired
private StringRedisTemplate redis1StringRedisTemplate;
@Autowired
private StringRedisTemplate redis2StringRedisTemplate;
@Autowired
private StringRedisTemplate redis3StringRedisTemplate;
@Autowired
private StringRedisTemplate redis4StringRedisTemplate;




请问咱们配置类的注入规则是什么样的，如果我配置了redis0-redis4,我在 MethodLimit类中只注入一个redis0  这样也可以嘛  如果可以，那我别的公共类是不是也可以这样注入了
@component
public class MethodLimit {
@Autowired
private StringRedisTemplate redis0StringRedisTemplate;

**Comment by Junya520** [comment]
感觉只注入 一个的话比较方便    yml配置几个  这样注入几个   还要修改源代码  修改的地方比较多

**Comment by Junya520** [comment]
感谢您的耐心解答  很有帮助  点个星

**Comment by louislivi** [comment]
只要注入变量名或者使用@Qualifier 你想用哪一个源直接注入对应的也是可以的。 工具类只是为了方便如果再一个类中要用多个源 可以只用注入一次。
