### ISSUE TITLE
redis 多数据源指定的configuration 配置就不生效了, 能够有解决方法吗?

### ISSUE THREAD

**Issue by tony-is-coding** [louislivi/fastdep#20]
我按照blog[https://blog.csdn.net/QQ2352108083/article/details/106106625] 的 配置去做了 ； 但是我的spring redis config 配置过期时间就不生效了; 能有好的解决方法吗？
![image](https://user-images.githubusercontent.com/34122761/104081126-916ed100-5267-11eb-9cb1-16807ed2d4f9.png)
上面是我的配置

**Comment by louislivi** [comment]
@tony-is-coding 
缓存使用不生效可以查看相关文档进行排查，本依赖只是用于解决了Redis多数据源配置，本身不影响缓存等使用，也并没有默认指定缓存相关配置项。

**Comment by tony-is-coding** [comment]
![image](https://user-images.githubusercontent.com/34122761/104081774-d432a800-526b-11eb-9db8-1bca7cf64d38.png)

**Comment by tony-is-coding** [comment]
好的，感谢
