### ISSUE TITLE
连接泄露，请教一下分布式事务的配置是否有问题

### ISSUE THREAD

**Issue by HanhongWang** [louislivi/fastdep#21]
### yml文件的配置:

**fastdep:
  datasource:
    base:
      mapper: com.whh.druid.mapper.base
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:xxx
      username: xxx
      password: xxx
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      keepAlive: true
      filters: stat,wall,slf4j**
### jta事务的配置类
`@Configuration
@EnableTransactionManagement
public class JTAConfig {
    @Bean
    @Primary
    public JtaTransactionManager jtaTransactionManager() throws SystemException {
        UserTransactionImp userTransactionImp = new UserTransactionImp();
        userTransactionImp.setTransactionTimeout(600);
        JtaTransactionManager jta = new JtaTransactionManager();
        jta.setUserTransaction(userTransactionImp);

//        jta.setDefaultTimeout(600);
        return jta;
    }
}`
### 控制台报错：
**2021-01-29 10:17:55.178 ERROR 5048 --- [stroy-635543541] com.alibaba.druid.pool.DruidDataSource   : abandon connection, owner thread: http-nio-8390-exec-7, connected at : 1611884869216, open stackTrace**

**Comment by louislivi** [comment]
不配置JTAConfig 是否正常呢

**Comment by louislivi** [comment]
看这个错误，貌似和全局事物无关

**Comment by HanhongWang** [comment]
@louislivi 不配置JTAConfig也不正常，我又做了另外一个测试:不引用fastdep-datasource,单独引用druid-spring-boot-starter、mybatis-spring-boot-starter、spring-boot-starter-jta-atomikos，就不存在连接泄露的问题，请问一下我的fastdep配置有问题吗？
### <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.1.21</version>
        </dependency>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>1.3.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jta-atomikos</artifactId>
            <version>2.4.2</version>
        </dependency>

**Comment by louislivi** [comment]
@WangHanHong 这个看着应该是`removeAbandoned `的问题

**Comment by louislivi** [comment]
`removeAbandoned`配置会引发这个问题，建议查看相关问题进行解决。

**Comment by HanhongWang** [comment]
@louislivi removeAbandond是打开的，他的作用是强制回收连接，但是我的代码就是一个简单的查询`    @RequestMapping("getModel")
    public String getModel(String id) {
        List<MsgModel> models = modelMapper.listMsgModelByCondition(new HashMap<String, Object>() {{
            put("id", id);
        }});
        return models.get(0).getContent();
    }`不存在慢查询的问题，而且我把removeAbandonedTimeout设成了1800s，sql的查询时间在这个范围内，我的业务代码应该不会造成连接泄露，我打开druid的监控显示 始终有6个连接未释放

**Comment by louislivi** [comment]
removeAbandoned是连接池的高级功能，理论上这中配置不应该出现在实际的生产环境，因为有时应用程序执行长事务，可能这种情况下，会被连接池误回收，该种配置一般在程序测试阶段，为了定位连接泄漏的具体代码位置，被开启。生产环境中连接的关闭应该靠程序自己保证。

**Comment by louislivi** [comment]
问题的原因不明，也有可能是兼容问题，可以查看源码中进行确认，但是`fastdep`做到的仅仅是注入bean的操作，并未针对`druid`或者其他依赖相关配置以及源码修改。
