### ISSUE TITLE
文件上传和下载模块 遇到问题

### ISSUE THREAD

**Issue by ghost** [louislivi/fastdep#23]
上传后是返回相应的下载链接了
`{
    "fileName": "灰.jpg",
    "fileDownloadUri": "http://127.0.0.1:8080/fd/file/download%5C%E7%81%B0.jpg",
    "originName": "灰.jpg",
    "size": 1270
}`
但是打开这个下载链接，响应的是
` HTTP Status 400 – Bad Request `

请问是还需要配置什么吗？

**Comment by louislivi** [comment]
`fileDownloadUri`少了个`/` 看看是不是配置过`downloadUrl`之类的呢？
