### ISSUE TITLE
全局事务失效

### ISSUE THREAD

**Issue by HanhongWang** [louislivi/fastdep#25]
yml文件

fastdep:
  datasource:
    oracle:
      mapper: com.whh.mapper.oracle
      #   数据源基本配置
      url: jdbc:oracle:thin:xxx
      username: xxx
      password: xxx
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1 FROM DUAL
      validationQueryTimeout: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      type: com.alibaba.druid.pool.DruidDataSource
    mysql:
      mapper: com.whh.mapper.mysql
      #   数据源基本配置
      url: jdbc:mysql://192.168.61.138:3306/whh?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1
      validationQueryTimeout: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql= true;druid.stat.slowSqlMillis= 5000
      useGlobalDataSourceStat: true
      type: com.alibaba.druid.pool.DruidDataSource

依赖
        <dependency>
            <groupId>com.louislivi.fastdep</groupId>
            <artifactId>fastdep-datasource</artifactId>
            <version>1.0.5</version>
        </dependency>

代码

    @Transactional(value = "txManager")
    public void service() {
        Map<String, Object> map = new HashMap<>();
        map.put("userName", "王永珀");
        map.put("roleName", "队长");
        map.put("ID", 2);
        map.put("USERNAME", "yuHan");
        map.put("PASSWORD", "男");
        map.put("NAME", "男");
        map.put("SEX", "男");
        map.put("FROMID", "1");
        oracleMapper.addMsg(map);
        List<Map<String, Object>> list = oracleMapper.select();
        mysqlMapper.addUser(map);
        int i = 1 / 0;
    }

**Comment by louislivi** [comment]
跨不同数据库设备XA事物应该无法实现。

**Comment by louislivi** [comment]
@WangHanHong 跨不同数据库设备XA事物应该无法实现，XA仅能跨数据库连接（同一数据库设备）。

**Comment by louislivi** [comment]
你也可以使用1.0.6的版本再试一次，1.0.6修复了全局事物有可能不生效的问题。
