### ISSUE TITLE
JwtUtil properties注入问题

### ISSUE THREAD

**Issue by pipi99** [louislivi/fastdep#4]
在网站的 JwtUtil 样例中。
@Resource
    public FastDepShiroJwt fastDepShiroJwt;

这个类不存在，发现应该是

@Resource
    public FastDepShiroJwtProperties fastDepShiroJwt;

**Comment by louislivi** [comment]
感谢反馈，已修复。 a407dbfc1016be4d094c92664423248e8bb61706
