### ISSUE TITLE
registerBeanDefinitions方法会多次执行

### ISSUE THREAD

**Issue by RysisLiang** [louislivi/fastdep#5]
第一次执行registerBeanDefinitions方法时 
`multipleRedis = binder.bind("fastdep.redis", Map.class).get(); `是可以解析到参数的。
但是bean都注册完毕后，还是会触发registerBeanDefinitions函数，并且上面那步会报错，
`java.util.NoSuchElementException: No value bound`

**Comment by louislivi** [comment]
贴出配置文件以及完整的错误日志
