### ISSUE TITLE
fastdep-datasource数据源密码配置用jasypt加密，不能正常解密

### ISSUE THREAD

**Issue by RobertJin123** [louislivi/fastdep#6]
密码用jasypt加密后为NIh07gz/trWZBR2UQYog/ThuGvye6Q0O，然后加上ENC，将数据库密码配置为ENC(NIh07gz/trWZBR2UQYog/ThuGvye6Q0O)后，连接数据库失败，应该是密码没有解密，这种该怎么处理？

**Comment by louislivi** [comment]
是的，未进行jasypt模块整合
