### ISSUE TITLE
fastdep-file，按照默认配置能上传图片不能访问

### ISSUE THREAD

**Issue by Lisichenghah** [louislivi/fastdep#9]
{
    "fileName": "1CA71495-BB56-4fcf-B143-852A6A449F8C.png",
    "fileDownloadUri": "http://localhost:8080/fd/file/download/2020/09/16%5C1CA71495-BB56-4fcf-B143-852A6A449F8C.png",
    "originName": "1CA71495-BB56-4fcf-B143-852A6A449F8C.png",
    "size": 817597
}
![image](https://user-images.githubusercontent.com/50938455/93322491-f2504480-f845-11ea-887e-9e796c06555e.png)
且不能设置servlet.context-path

**Comment by louislivi** [comment]
可能是你的web服务器其他配置导致了路径访问错误的问题
